### Create product
POST http://localhost:8080/api/products/create
Content-Type: application/json

{
  "name": "iphone Pro 30",
  "description": "Apple laptop för utvecklare",
  "price": 29999.99,
  "currency": "SEK",
  "categoryId": null,
  "categoryName": "Electronik",
  "stockQuantity": 10,
  "attributes": {
    "color": "space gray",
    "ram": "32GB",
    "storage": "1TB SSD"
  },
  "imageUrls": [
    "https://example.com/images/macbook.jpg"
  ]
}
